# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/88abdd91-072e-4d82-9c6b-28196fcfd96e";
    fsType = "ext4";
  };

  # https://wiki.nixos.org/wiki/Dual_Booting_NixOS_and_Windows
  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/8838-606F"; # nix-windows shared efi
    fsType = "vfat";
  };

  # for whatever other shit nix needs to store. windows efi doesnt need it.
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3555-7663";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/09ac00dc-0d54-42fe-8dfc-841f1ead296b";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
